networks:
  dev:
services: 
  nginx: 
    image: nginx:stable-alpine
    ports: 
      - "80:80"
    networks:
      - dev
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - frontend
  frontend:
    build: 
      context: ./frontend
    volumes:
      - node_modules:/app/node_modules
    networks:
      - dev
    container_name: sashenkaApp_f
